# Generated by Django 4.0.6 on 2022-08-02 10:21

from django.db import migrations
import utils.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mafia',
            name='icon',
            field=utils.customfields.ContentTypeRestrictedFileField(blank=True, default='mafia-dashboards/default-loner-icon.svg', null=True, upload_to='mafia-dashboards/'),
        ),
    ]
