# Generated by Django 4.0.6 on 2022-07-18 03:16

from django.db import migrations
import utils.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0005_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mafia',
            name='icon',
            field=utils.customfields.ContentTypeRestrictedFileField(blank=True, default='mafia-dashboards/loner-icon.svg', null=True, upload_to='mafia-dashboards/'),
        ),
    ]
