# Generated by Django 4.0.6 on 2022-07-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0009_alter_mafia_tag_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule',
            field=models.CharField(max_length=100),
        ),
    ]
