# Generated by Django 4.0.6 on 2022-07-27 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mafia', '0013_alter_mafia_color_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BanUserFrommafia',
            new_name='BanUserFromMafia',
        ),
    ]
