# Generated by Django 4.0.6 on 2022-07-14 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_message_user_space_rule_reaction_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
