# Generated by Django 4.0.6 on 2022-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_alter_space_color_theme_alter_space_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'rocket')], default=0),
        ),
    ]
