# Generated by Django 4.0.6 on 2022-07-18 03:16

from django.db import migrations
import utils.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_reaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=utils.customfields.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='chat-media/'),
        ),
    ]
