# Generated by Django 4.0.6 on 2022-07-18 03:16

from django.db import migrations
import utils.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='icon',
            field=utils.customfields.ContentTypeRestrictedFileField(blank=True, default='space-dashboards/loner-icon.svg', null=True, upload_to='space-dashboards/'),
        ),
    ]
