# Generated by Django 4.0.6 on 2022-07-19 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_alter_space_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='tag_line',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
