# Generated by Django 4.0.6 on 2022-07-25 03:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import utils.customfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0010_alter_rule_rule'),
    ]

    operations = [
        migrations.RenameModel('space', 'mafia'),
        migrations.AlterModelOptions(
            name='mafia',
            options={'verbose_name': 'mafia', 'verbose_name_plural': 'mafias'} 
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'mafia rule', 'verbose_name_plural': 'mafia rules'},
        ),
        migrations.RenameField(
            model_name='banuserfromspace',
            old_name='space',
            new_name='mafia'
        ),
        migrations.RenameField(
            model_name='message',
            old_name='space',
            new_name='mafia'
        ),
        migrations.RenameField(
            model_name='moderator',
            old_name='space',
            new_name='mafia'
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='space',
            new_name='mafia'
        ),
    ]
