# Generated by Django 4.0.6 on 2022-07-26 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0012_alter_mafia_background_image_alter_mafia_color_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mafia',
            name='color_theme',
            field=models.CharField(default='#ffffff00', max_length=16, validators=[django.core.validators.RegexValidator(code=400, message='not a valid hex color code', regex='^#(?:[0-9a-fA-F]{3,4}){1,2}$')]),
        ),
    ]
