# Generated by Django 4.0.6 on 2022-07-14 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedip',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blacklistedip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='tag_line',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blacklistedip',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
