# Generated by Django 4.0.6 on 2022-07-14 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_avatar_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=utils.customfields.ContentTypeRestrictedFileField(default='avatars/avatar-default.svg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
