# Generated by Django 4.0.6 on 2022-07-15 03:37

import django.core.validators
from django.db import migrations, models
import utils.customfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_blacklistedip_user_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=utils.customfields.ContentTypeRestrictedFileField(default='avatars/avatar-default.svg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(code=400, message='can contain only alpha numeric and -, _ and must begin with alphabet', regex='^[a-zA-Z][a-zA-Z0-9_-]+$')]),
        ),
    ]
