# Generated by Django 4.0.6 on 2022-07-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_avatar_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedip',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.0.0'),
            preserve_default=False,
        ),
    ]
